name: "CI"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Use Node.js 21.4.0
          uses: actions/setup-node@v2
          with:
            node-version: 21.4.0
            cache: 'npm'
            cache-dependency-path: package-lock.json
        
        - name: Install dependencies
          run: npm install
        
        - name: Run tests
          run: npm test